openapi: 3.0.1
info:
  title: Products API
  description: Products API for Hipster Application
  version: "1"
servers:
  - url: #replace-with-your-apigee-env-group#
paths:
  /products:
    get:
      tags:
      - ProductCatalogService
      operationId: GetProducts
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hipstershopListProductsResponse'
  /products/{productId}:
    get:
      tags:
      - ProductCatalogService
      operationId: GetProductDetails
      parameters:
      - name: productId
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hipstershopProduct'
components:
  schemas:
    hipstershopListProductsResponse:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/hipstershopProduct'
    hipstershopMoney:
      type: object
      properties:
        currency_code:
          type: string
          description: The 3-letter currency code defined in ISO 4217.
        units:
          type: string
          description: |-
            The whole units of the amount.
            For example if `currencyCode` is `"USD"`, then 1 unit is one US dollar.
          format: int64
        nanos:
          type: integer
          description: |-
            Number of nano (10^-9) units of the amount.
            The value must be between -999,999,999 and +999,999,999 inclusive.
            If `units` is positive, `nanos` must be positive or zero.
            If `units` is zero, `nanos` can be positive, zero, or negative.
            If `units` is negative, `nanos` must be negative or zero.
            For example $-1.75 is represented as `units`=-1 and `nanos`=-750,000,000.
          format: int32
      description: Represents an amount of money with its currency type.
    hipstershopProduct:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        picture:
          type: string
        price_usd:
          $ref: '#/components/schemas/hipstershopMoney'
        categories:
          type: array
          description: |-
            Categories such as "vintage" or "gardening" that can be used to look up
            other related products.
          items:
            type: string
